import type { Company } from "../types";

export const fetchCompanies = (): Company[] => {
    return [
        {
            id: "1",
            name: "TechViet Solutions",
            coverUrl: "https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/company_covers/cong-ty-co-phan-vien-thong-fpt-31f41267723f53b5a2973c4446b2151d-5fc9dbf2594f4.jpg",
            logoUrl: "https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/company_logos/cong-ty-co-phan-vien-thong-fpt-5d5f5980e317c.jpg",
            industry: "IT Services",
            location: "Ho Chi Minh, VN",
            rating: 4.8,
            reviews: 124,
            bio: "Leading software development company specializing in web and mobile applications for global clients.",
            openProjects: 12,
            collaboratedTalents: 89,
            isFollowed: false,
        },
        {
            id: "2",
            name: "FinanceFlow",
            coverUrl: "https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/company_covers/cong-ty-co-phan-vien-thong-fpt-31f41267723f53b5a2973c4446b2151d-5fc9dbf2594f4.jpg",
            logoUrl: "https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/company_logos/cong-ty-co-phan-vien-thong-fpt-5d5f5980e317c.jpg",
            industry: "Fintech",
            location: "Ha Noi, VN",
            rating: 4.6,
            reviews: 67,
            bio: "Revolutionary fintech platform providing seamless payment solutions and financials services.",
            openProjects: 8,
            collaboratedTalents: 45,
            isFollowed: true,
        },
        {
            id: "3",
            name: "ShopSmart",
            coverUrl: "https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/company_covers/cong-ty-co-phan-vien-thong-fpt-31f41267723f53b5a2973c4446b2151d-5fc9dbf2594f4.jpg",
            logoUrl: "https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/company_logos/cong-ty-co-phan-vien-thong-fpt-5d5f5980e317c.jpg",
            industry: "E-commerce",
            location: "Da Nang, VN",
            rating: 4.9,
            reviews: 203,
            bio: "Vietnam's fastest-growing e-commerce platform connecting millions of buyers and sellers nationwide.",
            openProjects: 25,
            collaboratedTalents: 156,
            isFollowed: false,
        },
        {
            id: "4",
            name: "GameStudio VN",
            coverUrl: "https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/company_covers/cong-ty-co-phan-vien-thong-fpt-31f41267723f53b5a2973c4446b2151d-5fc9dbf2594f4.jpg",
            logoUrl: "https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/company_logos/cong-ty-co-phan-vien-thong-fpt-5d5f5980e317c.jpg",
            industry: "Game",
            location: "Ho Chi Minh, VN",
            rating: 4.4,
            reviews: 32,
            bio: "Indie game studio creating immersive mobile and PC games with unique Vietnamese cultural elements.",
            openProjects: 3,
            collaboratedTalents: 18,
            isFollowed: false,
        },
        {
            id: "5",
            name: "AI Innovations",
            coverUrl: "https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/company_covers/cong-ty-co-phan-vien-thong-fpt-31f41267723f53b5a2973c4446b2151d-5fc9dbf2594f4.jpg",
            logoUrl: "https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/company_logos/cong-ty-co-phan-vien-thong-fpt-5d5f5980e317c.jpg",
            industry: "AI/ML",
            location: "Ho Chi Minh, VN",
            rating: 4.7,
            reviews: 89,
            bio: "Cutting-edge AI research and development company focusing on machine learning solutions for enterprises.",
            openProjects: 15,
            collaboratedTalents: 67,
            isFollowed: true,
        },
        {
            id: "6",
            name: "CloudTech Asia",
            coverUrl: "https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/company_covers/cong-ty-co-phan-vien-thong-fpt-31f41267723f53b5a2973c4446b2151d-5fc9dbf2594f4.jpg",
            logoUrl: "https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/company_logos/cong-ty-co-phan-vien-thong-fpt-5d5f5980e317c.jpg",
            industry: "IT Services",
            location: "Singapore",
            rating: 4.5,
            reviews: 145,
            bio: "Premier cloud infrastructure provider offering scalable solutions for businesses across Southeast Asia.",
            openProjects: 18,
            collaboratedTalents: 112,
            isFollowed: false,
        },
        {
            id: "7",
            name: "CryptoVault",
            coverUrl: "https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/company_covers/cong-ty-co-phan-vien-thong-fpt-31f41267723f53b5a2973c4446b2151d-5fc9dbf2594f4.jpg",
            logoUrl: "https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/company_logos/cong-ty-co-phan-vien-thong-fpt-5d5f5980e317c.jpg",
            industry: "Fintech",
            location: "Ha Noi, VN",
            rating: 4.2,
            reviews: 28,
            bio: "Secure cryptocurrency exchange platform with advanced trading features and wallet services.",
            openProjects: 5,
            collaboratedTalents: 23,
            isFollowed: false,
        },
        {
            id: "8",
            name: "MarketPlace Pro",
            coverUrl: "https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/company_covers/cong-ty-co-phan-vien-thong-fpt-31f41267723f53b5a2973c4446b2151d-5fc9dbf2594f4.jpg",
            logoUrl: "https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/company_logos/cong-ty-co-phan-vien-thong-fpt-5d5f5980e317c.jpg",
            industry: "E-commerce",
            location: "Bangkok, TH",
            rating: 4.8,
            reviews: 267,
            bio: "B2B marketplace connecting suppliers and retailers with advanced inventory management systems.",
            openProjects: 32,
            collaboratedTalents: 198,
            isFollowed: true,
        },
        {
            id: "9",
            name: "MobileGames Co",
            coverUrl: "https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/company_covers/cong-ty-co-phan-vien-thong-fpt-31f41267723f53b5a2973c4446b2151d-5fc9dbf2594f4.jpg",
            logoUrl: "https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/company_logos/cong-ty-co-phan-vien-thong-fpt-5d5f5980e317c.jpg",
            industry: "Game",
            location: "Ho Chi Minh, VN",
            rating: 4.3,
            reviews: 56,
            bio: "Mobile game publisher specializing in casual and strategy games with millions of downloads worldwide.",
            openProjects: 7,
            collaboratedTalents: 34,
            isFollowed: false,
        },
        {
            id: "10",
            name: "DataMind",
            coverUrl: "https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/company_covers/cong-ty-co-phan-vien-thong-fpt-31f41267723f53b5a2973c4446b2151d-5fc9dbf2594f4.jpg",
            logoUrl: "https://cdn-new.topcv.vn/unsafe/https://static.topcv.vn/company_logos/cong-ty-co-phan-vien-thong-fpt-5d5f5980e317c.jpg",
            industry: "AI/ML",
            location: "Singapore",
            rating: 4.9,
            reviews: 178,
            bio: "Data science consultancy providing advanced analytics and machine learning solutions for Fortune 500 companies.",
            openProjects: 22,
            collaboratedTalents: 134,
            isFollowed: false,
        }
    ];
};