export enum MilestoneStatus {
    PENDING = 'PENDING',
    PENDING_START = 'PENDING_START',
    UPDATE_REQUIRED = 'UPDATE_REQUIRED',
    ON_GOING = 'ON_GOING',
    PENDING_COMPLETED = 'PENDING_COMPLETED',
    COMPLETED = 'COMPLETED',
    UPDATE_COMPLETED = 'UPDATE_COMPLETED',
    PENDING_DEPOSIT = 'PENDING_DEPOSIT',
    DEPOSITED = 'DEPOSITED',
    PAID = 'PAID',
    RELEASED = 'RELEASED',
}

export enum MilestoneExtensionRequestStatus {
    PENDING = 'PENDING',
    REJECTED = 'REJECTED',
    APPROVED = 'APPROVED',
}