export enum MilestoneStatus {
    PENDING = 'PENDING',
    PENDING_START = 'PENDING_START',
    UPDATE_REQUIRED = 'UPDATE_REQUIRED',
    ON_GOING = 'ON_GOING',
    PENDING_COMPLETED = 'PENDING_COMPLETED',
    COMPLETED = 'COMPLETED',
    PAID = 'PAID',
    DISTRIBUTED = 'DISTRIBUTED',
}

export enum MilestoneExtensionRequestStatus {
    PENDING = 'PENDING',
    REJECTED = 'REJECTED',
    APPROVED = 'APPROVED',
}